### ISSUE TITLE
GL library fallback for GLX broken in 3.1.7

### ISSUE THREAD

**Issue by swt2c** [mcfletch/pyopengl#101]
The fallback from `OpenGL` to `GL` for the GLX platform doesn't work in 3.1.7.  This is because the `ctypesloader.loadLibrary` doesn't throw exceptions when the library can't be found (perhaps it did at one point???).  So, either `ctypesloader.loadLibrary` should be updated to throw exceptions, or GLX should be updated to match EGL, where EGL supports both library names but doesn't check for exceptions.

https://github.com/mcfletch/pyopengl/blob/master/OpenGL/platform/glx.py#L13

**Comment by mcfletch** [comment]
Okay, updated the glx to check for glx, opengl and gl when doing glx lookup, and opengl and gl for opengl lookup.

**Comment by mcfletch** [comment]
They are in develop head, will show up in the next release. I'm currently working through the ticket backlog to see what else I can get addressed in my day-or-so of available time.
