### ISSUE TITLE
PyOpenGL version 3.1.3b2 AttributeError

### ISSUE THREAD

**Issue by djhoese** [mcfletch/pyopengl#19]
I first reported this on conda-forge where I was getting the package from: https://github.com/conda-forge/pyopengl-feedstock/issues/16

I'm using pyopengl in the vispy project and have Travis CI run tests weekly. Recently it started failing when pyopengl was switched from version 3.1.1a1 to version 3.1.3b2 with the following error for most of our operations:

```
self = <OpenGL.converters.SizedOutputOrInput object at 0x2b7757b86af0>
result = None
baseOperation = <OpenGL.platform.baseplatform.glGetBufferParameteriv object at 0x2b7757b0c7e8>
pyArgs = (GL_ARRAY_BUFFER, GL_BUFFER_SIZE, <object object at 0x2b7755acf6e0>)
cArgs = (GL_ARRAY_BUFFER, GL_BUFFER_SIZE, array([192], dtype=int32))
    def oldStyleReturn( self, result, baseOperation, pyArgs, cArgs ):
        """Retrieve cArgs[ self.index ]"""
>       result = cArgs[ self.outIndex ]
E       AttributeError: ('outIndex', <bound method SizedOutputOrInput.oldStyleReturn of <OpenGL.converters.SizedOutputOrInput object at 0x2b7757b86af0>>, (None, <OpenGL.platform.baseplatform.glGetBufferParameteriv object at 0x2b7757b0c7e8>, (GL_ARRAY_BUFFER, GL_BUFFER_SIZE, <object object at 0x2b7755acf6e0>), (GL_ARRAY_BUFFER, GL_BUFFER_SIZE, array([192], dtype=int32))), {})
../../../anaconda/envs/testenv/lib/python2.7/site-packages/OpenGL/converters.py:202: AttributeError
```

Any idea what may have changed to cause this? I also noticed 3.1.3 are the first releases since 2015 on PyPI so maybe that is an issue.

**Comment by mcfletch** [comment]
At the moment I can't reproduce the failure on my machine. There are 3 failures in pytest on the gloo test-suite, but they aren't the error above (using either of master branch from bzr or the 3.1.3b2 release from pypi). The outIndex element *should* be there in the component, and it *seems* to be there when I test with this:

`python -c "from OpenGL.GL import glGetBufferParameteriv;glGetBufferParameteriv.finalise();print(glGetBufferParameteriv.cConverters[-1].outIndex)"`

for both bzr master on py27 with accelerate and pypi current beta in a virtualenv. outIndex should be created by the superclass SizedOutput which has an indexLookups which includes 'outIndex', which means that it should be populated in the finalise() call to the function wrapper.

Is it possible to run the above operation in your travis environment? If the simple test is failing there, then we've likely got something environmental/setup related, or maybe version skew, though I don't see where that would apply precisely.

**Comment by djhoese** [comment]
@mcfletch Thanks for trying to debug this. I'll add that line to the tests and we'll see what happens.

**Comment by djhoese** [comment]
@mcfletch Looks like that worked: https://travis-ci.org/vispy/vispy/builds/483898167

Could you point me to the git commit on this repository that is equivalent to 3.1.1a1? Maybe I can walkthrough installing commits until the tests start failing and see what causes the issue.

**Comment by djhoese** [comment]
@mcfletch Any idea which commit corresponds to 3.1.1a1?

**Comment by kmuehlbauer** [comment]
@mcfletch While poking around to get to the source problem, I found this redefinition of `glGetBufferParameteriv`-wrapper [here](https://github.com/mcfletch/pyopengl/blob/bf11e7e59bff4a57dffbe79e1b27dac5a09166fc/OpenGL/GL/VERSION/GL_1_5.py#L127)

When removing these redefinition the error went away.

**Comment by mcfletch** [comment]
From the comment on #20 it seems this should be closed.
