### ISSUE TITLE
No `GL_RG_INTEGER` in `OpenGL.images.COMPONENT_COUNTS` dictionary

### ISSUE THREAD

**Issue by v3c70r** [mcfletch/pyopengl#2]
I triggered a bug while trying to call `glGetTexImage` with `GL_RG_INTEGER` format. It throws ValueError: Unrecognised image format: GL_RG_INTEGER since  `GL_RG_INTEGER` is not in `OpenGL.images.COMPONENT_COUNTS`. I hacked it around by adding it to the dictionary and it works.

**Comment by mcfletch** [comment]
This should be in the current release.
