### ISSUE TITLE
Is pyOpenGL only for Windows users?

### ISSUE THREAD

**Issue by apenngrace** [mcfletch/pyopengl#24]
When using **pip** to install pyOpenGL (versions from 3.1.0 to latest 0b2) has a version of `ctypesloader.py` that only looks for windows `dll` files:

```
"""ctypes abstraction layer

We keep rewriting functions as the main entry points change,
so let's just localise the changes here...
"""
import ctypes, logging, os, sys
_log = logging.getLogger( 'OpenGL.platform.ctypesloader' )
#_log.setLevel( logging.DEBUG )
ctypes_version = [
    int(x) for x in ctypes.__version__.split('.')
]
from ctypes import util
import OpenGL

DLL_DIRECTORY = os.path.join( os.path.dirname( OpenGL.__file__ ), 'DLLS' )

def loadLibrary( dllType, name, mode = ctypes.RTLD_GLOBAL ):
    """Load a given library by name with the given mode
    
    dllType -- the standard ctypes pointer to a dll type, such as
        ctypes.cdll or ctypes.windll or the underlying ctypes.CDLL or 
        ctypes.WinDLL classes.
    name -- a short module name, e.g. 'GL' or 'GLU'
    mode -- ctypes.RTLD_GLOBAL or ctypes.RTLD_LOCAL,
        controls whether the module resolves names via other
        modules already loaded into this process.  GL modules
        generally need to be loaded with GLOBAL flags
    
    returns the ctypes C-module object
    """
    if isinstance( dllType, ctypes.LibraryLoader ):
        dllType = dllType._dlltype
    fullName = None
    try:
        fullName = util.find_library( name )
        if fullName is not None:
            name = fullName
        elif os.path.isfile( os.path.join( DLL_DIRECTORY, name + '.dll' )):
            name = os.path.join( DLL_DIRECTORY, name + '.dll' )
    except Exception as err:
        _log.info( '''Failed on util.find_library( %r ): %s''', name, err )
        # Should the call fail, we just try to load the base filename...
        pass
    try:
        return dllType( name, mode )
    except Exception as err:
        err.args += (name,fullName)
        raise

def buildFunction( functionType, name, dll ):
    """Abstract away the ctypes function-creation operation"""
    return functionType( (name, dll), )
```

This is really weird, because past commits such as [commit 3379c7e](https://github.com/mcfletch/pyopengl/blob/3379c7e3260d0ae49c69336005926e5d49d9da20/OpenGL/platform/ctypesloader.py) had code for loading Linux, MacOS, and Windows library files, not just Windows `dll` files.

The code that comes from pip does not even match the code up on the Github repo.  Is there some sort of mix-up happening?

**Comment by mcfletch** [comment]
Actually, PyOpenGL is developed solely on *linux* and difficulties testing on Windows and Mac is one of the major reasons I never seem to get releases done. The commit that changed this code is bzr -r 1019, and it seems to have been one of those cases where I got an error report from a Mac user and made the change, relying on reports from users that it fixed mac issues.

My assumption from the report is that you are using a Mac, possibly using the system python? Does installing `pip install "PyOpenGL==3.1.3b2"` correct the issue?

**Comment by apenngrace** [comment]
I just tried `pip install "PyOpenGL==3.1.3b2"` using another machine running MacOS 10.4.4 (Mojave), and that worked no problem.  I'll try again on my High Sierra machine to try to figure out what the heck could be going on.

**Comment by jayvdb** [comment]
The pip package `PyOpenGL` is OS-independent . The pip package PyOpenGL-accelerate is the one with the platform-specific compiled bits.

Be aware that atm https://github.com/mcfletch/pyopengl/issues/28

**Comment by mcfletch** [comment]
Don't seem to have anything further actionable here. AFAIK the current release builds on OS-X
