### ISSUE TITLE
Problem: Headless rendering with nvidia and using libOpenGL.so

### ISSUE THREAD

**Issue by tasptz** [mcfletch/pyopengl#27]
How can I make pyopengl use `libOpenGL.so` and not `libGL.so`.
For detailed explanation see [Pro Tip: Linking OpenGL for Server-Side Rendering](https://devblogs.nvidia.com/linking-opengl-server-side-rendering/).

> To use glX and OpenGL today, you should link against libOpenGL.so as well as libGLX.so. The first contains the OpenGL symbols, the latter the GLX symbols. If you want to use EGL context management instead, link against  libOpenGL.so and libEGL.so.

I used `lsof -p <pid>` and for sure the python process loaded `libGL.so` and thus the EGL-OpenGL context was not working.

**Comment by tasptz** [comment]
```diff
diff --git a/OpenGL/platform/egl.py b/OpenGL/platform/egl.py
index 8a92d018..d52f9157 100644
--- a/OpenGL/platform/egl.py
+++ b/OpenGL/platform/egl.py
@@ -33,7 +33,7 @@ class EGLPlatform( baseplatform.BasePlatform ):
         try:
             return ctypesloader.loadLibrary(
                 ctypes.cdll,
-                'GL', 
+                'OpenGL',
                 mode=ctypes.RTLD_GLOBAL 
             )
         except OSError:```

This seems to resolve the problem, but is probably not a universal solution.

**Comment by yaokxx** [comment]
It still do not work under my condition LOL, is there other solution? Or just my misunderstanding that i just change one line in  the source code of egl.py, just replace 'GL' with 'OpenGL'?
