### ISSUE TITLE
Source tarball for PyOpenGL-accelerate 3.1.5 missing on PyPI

### ISSUE THREAD

**Issue by swt2c** [mcfletch/pyopengl#37]
The source tarball for PyOpenGL-accelerate 3.1.5 is missing on PyPI.

**Comment by jmroot** [comment]
@mcfletch Ping. AFAICT this is preventing installation of PyOpenGL-accelerate on all non-Windows platforms.

**Comment by anibali** [comment]
I can confirm that this prevents installation of PyOpenGL-accelerate 3.1.5 on Ubuntu 18.04. Here's the error message generated by `pip`:

```
ERROR: Could not find a version that satisfies the requirement PyOpenGL-accelerate==3.1.5 (from -r requirements.txt (line 6)) (from versions: 3.0.1b1, 3.0.1b2, 3.0.1, 3.0.2a1, 3.0.2b2, 3.0.2, 3.1.0a1, 3.1.0a3, 3.1.0b1, 3.1.0b2, 3.1.0b3, 3.1.0, 3.1.1a1, 3.1.3b1, 3.1.3rc1, 3.1.4)
ERROR: No matching distribution found for PyOpenGL-accelerate==3.1.5 (from -r requirements.txt (line 6))
```

**Comment by swt2c** [comment]
Looks like this has been fixed.
