### ISSUE TITLE
OpenGL.error.GLError: GLError - err = 1281 - description = b'invalid value'

### ISSUE THREAD

**Issue by chwba** [mcfletch/pyopengl#53]
Im using https://github.com/swistakm/pyimgui, which uses this library and on clicking some custom keys on my Mouse (Logitech G502), I can consistently produce the following error, which crashes the application, any ideas?

Do note, that one of the custom keys will trigger the Windows action to "Show the Desktop", meaning minimize all windows and I believe its related to that, at least it seems like it.

Im using Python 3.9 on Windows 10 - 2004 with pyopengl 3.1.5.

```python
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glScissor,
	cArguments = (81, 1, -35, 727)
)
```

I tried to put `OpenGL.ERROR_CHECKING = False` but that didn't do the trick yet.

**Comment by chwba** [comment]
bump

**Comment by mcfletch** [comment]
Well the docs at http://mcfletch.github.io/pyopengl/documentation/manual/glScissor.html state that width or height being negative will cause an invalid value to be reported. width (the 3rd parameter) is -35, and it is generating an invalid parameter... so the upper levels of code (i.e. pyimgui) would need to look at the values and decide what to do when there is a negative value based on the logic of the application. PyOpenGL here isn't actually doing anything other than forwarding data from the app to the C api, so it doesn't really have any control over the behaviour described.

HTH

**Comment by chwba** [comment]
Thanks for clarifying
