### ISSUE TITLE
Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

### ISSUE THREAD

**Issue by ultraflame4** [mcfletch/pyopengl#57]
Error: `OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling`

Python version: 3.8
pyopengl : 3.1.5
OS: windows 10

I got this error  while trying to run this piece of code, ( im following a [tutorial](https://stackabuse.com/brief-introduction-to-opengl-in-python-with-pyopengl/) )

```
glutInit()  # Initialize a glut instance which will allow us to customize our window

glutInitDisplayMode(GLUT_RGBA)  # Set the display mode to be colored

glutInitWindowSize(500, 500)  # Set the width and height of your window

glutInitWindowPosition(0, 0)  # Set the position at which this windows should appear

wind = glutCreateWindow("OpenGL Coding Practice")  # Give your window a title

glutDisplayFunc(showScreen)  # Tell OpenGL to call the showScreen method continuously

glutIdleFunc(showScreen)  # Draw any graphics or shapes in the showScreen function at all times

glutMainLoop()  # Keeps the window created above displaying/running in a loop

```

**Comment by mcfletch** [comment]
Do you have GLUT or FreeGLUT installed on your machine? The `glutInit()` function is provided by those third-party packages (not included with Windows by default) and PyOpenGL's `OpenGL.GLUT` is just a wrapper around those third-party libraries. My understanding is that FreeGLUT is the generally preferred version and that it is currently available here: https://www.transmissionzero.co.uk/software/freeglut-devel/

However, I'm not a windows user, so it is possible that I'm missing some underlying regression.

**Comment by ultraflame4** [comment]
I've tried installing freeGlut, i kinda went down a rabbit hole with that. in the end i gave up n watch a youtube tut. it works now. thanks!

**Comment by sldsmkd** [comment]
> I've tried installing freeGlut, i kinda went down a rabbit hole with that. in the end i gave up n watch a youtube tut. it works now. thanks!

It would be helpful if you linked how you fixed it

**Comment by ormax3** [comment]
For anyone else having the same problem on windows, I suggest downloading the binaries from gohlke archive:

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl

they include freeglut and gle DLLs embedded inside the wheel

**Comment by Ashisheng2005** [comment]
I tried to get in https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyopengl，But it prompts me “The page you requested was removed.”

**Comment by Ashisheng2005** [comment]
I find it from https://pypi.funzilla.net/ , But only versions prior to 3.11

**Comment by digitalnumeric** [comment]
This might help:
Christoph Gohlke recently created new Windows wheels here:
https://github.com/cgohlke/pyopengl-build
https://github.com/cgohlke/pyopengl-build/releases

**Comment by ormax3** [comment]
Yes it seems gohlke windows builds have sadly been discontinued:

https://old.reddit.com/r/Python/comments/vcaibq/christoph_gohlkes_windows_wheels_site_is_shutting/

He still maintains [only a few](https://www.cgohlke.com/), including pyopengl built on Github Actions:

https://github.com/cgohlke/pyopengl-build/blob/main/.github/workflows/wheel.yml
