### ISSUE TITLE
Python 3.9 cannot install pyopengl-accelerate. Log attached.

### ISSUE THREAD

**Issue by pallebone** [mcfletch/pyopengl#97]
Hi there,

On Debian in a virtual environemtn I cannot install pyopengl-accelerate via:
pip install pyopengl-accelerate --log /home/aragorn/log.txt

"python setup.py bdist_wheel did not run successfully."

The log is attached here:

Is this a known issue?

Kind regards
Peter
[log.txt](https://github.com/mcfletch/pyopengl/files/11435515/log.txt)

**Comment by gentlegiantJGC** [comment]
There were issues with pyopengl accelerate with Mac as well. Perhaps I should just disable it.
It is an optional dependency that makes part of pyopengl faster but I don't know if we use those parts.

**Comment by pallebone** [comment]
> There were issues with pyopengl accelerate with Mac as well. Perhaps I should just disable it. It is an optional dependency that makes part of pyopengl faster but I don't know if we use those parts.

If we cant get anywhere maybe but I will try fix this underlying issue first as it might help a lot of people.

**Comment by mcfletch** [comment]
I've attempted to get PyOpenGL-accelerate building using cibuildwheel for the 3.1.7 release. I'm hoping that will make it easier to install on the common platforms.

**Comment by pallebone** [comment]
Hello @mcfletch,

Thank you for responding to my issue. It is appreciated. 

I dont understand what you would like me to do. Can you provide more clarification? Are you asking me to use an older version of setuptools and retry or are you asking me to wait for a new version of pyopengl-accelerate and test that? 

Im happy to try either direction, please clarify what you want me to do and test.

Kind regards
Peter

**Comment by pallebone** [comment]
I saw there was an update to your package and was able to build against 3.1.7 successfully. Please allow me some days to do further testing and I will report back

**Comment by pallebone** [comment]
Thank you I can now build your package with setuptools              67.8.0
PyOpenGL-accelerate     3.1.7

Kind regards
Peter
